# Generated by Django 4.1.7 on 2023-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (1, 'Fine'), (1, 'Good'), (1, 'Amazing'), (1, 'Incredible')], null=True),
        ),
    ]
